app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
rest : 
  type : rest 
  resource: "@AppBundle/Resources/config/routing_rest.yml"
  prefix : /api
  options:
        expose: true

admin:
    resource: @SonataAdminBundle/Resources/config/routing/sonata_admin.xml
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
