<?php

namespace AppBundle\Entity;

use JMS\DiExtraBundle\Annotation as JMS;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
}
